### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
test

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example123: Refreshing state... (ID: 8173135262925815516)
null_resource.examples: Refreshing state... (ID: 1235548215495377011)
null_resource.example4099: Refreshing state... (ID: 4119078050475135845)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

- null_resource.example123

  + null_resource.example1233
      id: <computed>
Plan: 1 to add, 0 to change, 1 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Pull request closed without merging**
