### PR TITLE
Create main.tf

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
**Apply Failed**: Pull request must be approved before running apply.

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
null_resource.example: Creating...
null_resource.example: Creation complete after 0s (ID: 3832672341919723966)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
