### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
**Plan Failed**: This project is currently locked by #5. The locking plan must be applied or discarded before future plans can execute.

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example3: Refreshing state... (ID: 3338755005935589550)
null_resource.example2: Refreshing state... (ID: 6623752176838312381)
null_resource.examples: Refreshing state... (ID: 1235548215495377011)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

- null_resource.example3
Plan: 0 to add, 0 to change, 1 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by relateiq-ec2** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.examples: Refreshing state... (ID: 1235548215495377011)
null_resource.example2: Refreshing state... (ID: 6623752176838312381)
null_resource.example3: Refreshing state... (ID: 3338755005935589550)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

- null_resource.example2

  - null_resource.example3

  + null_resource.example94
      id: <computed>
Plan: 1 to add, 0 to change, 2 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
null_resource.example3: Destroying... (ID: 3338755005935589550)
null_resource.example2: Destroying... (ID: 6623752176838312381)
null_resource.example2: Destruction complete after 0s
null_resource.example3: Destruction complete after 0s
null_resource.example94: Creating...
null_resource.example94: Creation complete after 0s (ID: 174831182807967349)

Apply complete! Resources: 1 added, 0 changed, 2 destroyed.

```

**Pull request merged**
