### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/root/.atlantis/repos/relateiq/test-atlantis-webhook/17/default": 

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: null_resource.example1222: resource repeated multiple times



```

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/root/.atlantis/repos/relateiq/test-atlantis-webhook/17/default": 

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: null_resource.example1222: resource repeated multiple times



```

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/root/.atlantis/repos/relateiq/test-atlantis-webhook/17/default": 

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: null_resource.example1222: resource repeated multiple times



```

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example12: Refreshing state... (ID: 6680434669449837472)
null_resource.example99: Refreshing state... (ID: 3892098525437176043)
null_resource.examples: Refreshing state... (ID: 1235548215495377011)
null_resource.example1222: Refreshing state... (ID: 2306740760612140282)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example1232
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
null_resource.example1232: Creating...
null_resource.example1232: Creation complete after 0s (ID: 5025908097289238081)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by iq-pe-atlas** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `relateiq/test-atlantis-webhook/.` workspace: `default`

**Pull request merged**
