### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
**Plan Failed**: This project is currently locked by #9. The locking plan must be applied or discarded before future plans can execute.

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example4099: Refreshing state... (ID: 4119078050475135845)
null_resource.examples: Refreshing state... (ID: 1235548215495377011)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example123
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by relateiq-ec2** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
null_resource.example123: Creating...
null_resource.example123: Creation complete after 0s (ID: 8173135262925815516)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by iq-pe-atlas** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `relateiq/test-atlantis-webhook/.` workspace: `default`

**Pull request merged**
