### PR TITLE
adding sg to test

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
**Plan Failed**: This project is currently locked by #3. The locking plan must be applied or discarded before future plans can execute.

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_security_group.winstontest
      id:                     <computed>
      arn:                    <computed>
      description:            "winstontest"
      egress.#:               <computed>
      ingress.#:              <computed>
      name:                   "winstontest"
      owner_id:               <computed>
      revoke_rules_on_delete: "false"
      tags.%:                 "1"
      tags.Name:              "winstontest"
      vpc_id:                 <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by relateiq-ec2** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_security_group.winstontest
      id:                     <computed>
      arn:                    <computed>
      description:            "winstontest"
      egress.#:               <computed>
      ingress.#:              <computed>
      name:                   "winstontest"
      owner_id:               <computed>
      revoke_rules_on_delete: "false"
      tags.%:                 "1"
      tags.Name:              "winstontest"
      vpc_id:                 <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by relateiq-ec2** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
**Apply Error**
```
exit status 1: running "sh -c terraform apply -no-color /root/.atlantis/repos/relateiq/test-atlantis-webhook/4/default/default.tfplan" in "/root/.atlantis/repos/relateiq/test-atlantis-webhook/4/default": 
aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.winstontest: 1 error(s) occurred:

* aws_security_group.winstontest: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
	status code: 400, request id: 670f0312-20a4-45eb-8000-9fd181e4233a

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.winstontest: 1 error(s) occurred:

* aws_security_group.winstontest: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
	status code: 400, request id: 670f0312-20a4-45eb-8000-9fd181e4233a

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```

**Comment by relateiq-ec2** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_security_group.winstontest
      id:                     <computed>
      arn:                    <computed>
      description:            "winstontest"
      egress.#:               <computed>
      ingress.#:              <computed>
      name:                   "winstontest"
      owner_id:               <computed>
      revoke_rules_on_delete: "false"
      tags.%:                 "1"
      tags.Name:              "winstontest"
      vpc_id:                 <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by relateiq-ec2** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
**Apply Error**
```
exit status 1: running "sh -c terraform apply -no-color /root/.atlantis/repos/relateiq/test-atlantis-webhook/4/default/default.tfplan" in "/root/.atlantis/repos/relateiq/test-atlantis-webhook/4/default": 
aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.winstontest: 1 error(s) occurred:

* aws_security_group.winstontest: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
	status code: 400, request id: b1fb37e1-da9e-4e9a-ae49-cb5943500cd6

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.winstontest: 1 error(s) occurred:

* aws_security_group.winstontest: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
	status code: 400, request id: b1fb37e1-da9e-4e9a-ae49-cb5943500cd6

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_security_group.winstontest
      id:                     <computed>
      arn:                    <computed>
      description:            "winstontest"
      egress.#:               <computed>
      ingress.#:              <computed>
      name:                   "winstontest"
      owner_id:               <computed>
      revoke_rules_on_delete: "false"
      tags.%:                 "1"
      tags.Name:              "winstontest"
      vpc_id:                 "vpc-6329ac05"
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by iq-pe-atlas** [comment]
**Apply Error**
```
exit status 1: running "sh -c terraform apply -no-color /root/.atlantis/repos/relateiq/test-atlantis-webhook/4/default/default.tfplan" in "/root/.atlantis/repos/relateiq/test-atlantis-webhook/4/default": 
aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "vpc-6329ac05"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.winstontest: 1 error(s) occurred:

* aws_security_group.winstontest: Error creating Security Group: InvalidGroup.Duplicate: The security group 'winstontest' already exists for VPC 'vpc-6329ac05'
	status code: 400, request id: a1f79aea-50e2-4171-a977-a701b08d2cc5

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "vpc-6329ac05"

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.winstontest: 1 error(s) occurred:

* aws_security_group.winstontest: Error creating Security Group: InvalidGroup.Duplicate: The security group 'winstontest' already exists for VPC 'vpc-6329ac05'
	status code: 400, request id: a1f79aea-50e2-4171-a977-a701b08d2cc5

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



```

**Comment by relateiq-ec2** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_security_group.winstontest
      id:                     <computed>
      arn:                    <computed>
      description:            "winstontest"
      egress.#:               <computed>
      ingress.#:              <computed>
      name:                   "winstontest"
      owner_id:               <computed>
      revoke_rules_on_delete: "false"
      tags.%:                 "1"
      tags.Name:              "winstontest"
      vpc_id:                 "vpc-6329ac05"
Plan: 1 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by relateiq-ec2** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
**Apply Failed**: Pull request must be approved before running apply.

**Comment by relateiq-ec2** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
aws_security_group.winstontest: Creating...
  arn:                    "" => "<computed>"
  description:            "" => "winstontest"
  egress.#:               "" => "<computed>"
  ingress.#:              "" => "<computed>"
  name:                   "" => "winstontest"
  owner_id:               "" => "<computed>"
  revoke_rules_on_delete: "" => "false"
  tags.%:                 "" => "1"
  tags.Name:              "" => "winstontest"
  vpc_id:                 "" => "vpc-6329ac05"
aws_security_group.winstontest: Creation complete after 0s (ID: sg-cbaa38ba)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by relateiq-ec2** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
data.vault_generic_secret.atlantis-global: Refreshing state...
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Pull request merged**
