### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by DeanDean12**

### CODE REVIEW

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by relateiq-ec2** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

- null_resource.example

  + null_resource.examples
      id: <computed>
Plan: 1 to add, 0 to change, 1 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

- null_resource.example

  + null_resource.example2
      id: <computed>

  + null_resource.examples
      id: <computed>
Plan: 2 to add, 0 to change, 1 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.example: Refreshing state... (ID: 9169552626058296616)
aws_security_group.winstontest: Refreshing state... (ID: sg-cbaa38ba)
data.vault_generic_secret.atlantis-global: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

- null_resource.example

  + null_resource.example2
      id: <computed>

  + null_resource.example3
      id: <computed>

  + null_resource.examples
      id: <computed>
Plan: 3 to add, 0 to change, 1 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Ftest-atlantis-webhook%252F.%252Fdefault).

**Comment by DeanDean12** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
null_resource.example: Destroying... (ID: 9169552626058296616)
null_resource.example: Destruction complete after 0s
null_resource.example2: Creating...
null_resource.examples: Creating...
null_resource.example3: Creating...
null_resource.example2: Creation complete after 0s (ID: 6623752176838312381)
null_resource.example3: Creation complete after 0s (ID: 3338755005935589550)
null_resource.examples: Creation complete after 0s (ID: 1235548215495377011)

Apply complete! Resources: 3 added, 0 changed, 1 destroyed.

```

**Pull request merged**
